### ISSUE TITLE
Where is the file?

### ISSUE THREAD

**Issue by z4rn0x** [fransakeson/ESP32_iGrill#1]
Hello! I found your github very recently and I'm already excited to try it! If you need anybody to do some debug test, I could be the one! Let me know...

**Comment by fransakeson** [comment]
Hi, I'm still working on the initial (crappy) authentication required by the iGrill thermometers, but I'm not getting the expected response from the device. It's probably not a big problem, but I have limited time right now. Check back in a couple of weeks and hopefully I'll have something to share.

**Comment by z4rn0x** [comment]
Great, thank you!
